resources:
  - ../../base/
commonLabels:
  env: Dev
namespace: nginx-dev
namePrefix: dev-
nameSuffix: "-1"
commonAnnotations:
  oncallPager: 800-555-1111
  
#patchesStrategicMerge:
patches:
  - path: replica-count.yaml

images:
  - name: nginx
    newName: nginx
    newTag: stable-alpine